##########################################
# Global containers
##########################################

# phpmyadmin for admin database
'phpmyadmin':
    image: 'nazarpc/phpmyadmin:latest'
    container_name: 'phpmyadmin'
    environment:
      - ALLOW_ARBITRARY=1
      - URL=phpmyadmin.blog
    restart: always
    links: ['mysql_auth', 'mysql_blog']
    ports: ['30000:80']

# database for service `auth`
'mysql_auth':
    image: 'mysql:5.6.26'
    container_name: 'mysql_auth'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes: [/var/lib/mysql]

# database for service `Comment` and `Post`
'mysql_blog':
    image: 'mysql:5.6.26'
    container_name: 'mysql_blog'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes: [/var/lib/mysql]

# redis for fast cache
'redis':
    image: 'redis'
    container_name: 'redis'

##########################################
# Service `Gate`
##########################################

# source code storage for `gate`
'source_gate':
    build: 'source'
    container_name: 'source_gate'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Gate:/home/gregory/source/']

# php for `Gate`
'php_gate':
    build: 'php'
    container_name: 'php_gate'
    volumes_from: ['source_gate']
    volumes: ['./logs/php/gate/:/var/log/dev_php']
    links:
      - nginx_post_1:post1.blog
      - nginx_post_2:post2.blog
      - nginx_comment_1:comment1.blog
      - nginx_comment_2:comment2.blog
      - nginx_auth_1:auth1.blog
      - nginx_auth_2:auth2.blog
      - redis
    environment:
      - POST_1_HOST=post1.blog
      - POST_1_PORT=80
      - POST_2_HOST=post2.blog
      - POST_2_PORT=80
      - COMMENT_1_HOST=comment1.blog
      - COMMENT_1_PORT=80
      - COMMENT_2_HOST=comment2.blog
      - COMMENT_2_PORT=80
      - AUTH_1_HOST=auth1.blog
      - AUTH_1_PORT=80
      - AUTH_2_HOST=auth2.blog
      - AUTH_2_PORT=80

# nginx for `Gate`
'nginx_gate':
    build: 'nginx'
    container_name: 'nginx_gate'
    links: ['php_gate']
    volumes_from: ['source_gate']
    ports: ['30001:80']
    environment:
      - PHP_HOST=php_gate
      - NGINX_HOST_TEMPLATE=gate.blog
    volumes: ['./logs/nginx/gate/:/var/log/nginx']

##########################################
# Service `Post 1`
##########################################

# source code storage for `Post 1`
'source_post_1':
    build: 'source'
    container_name: 'source_post_1'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Post:/home/gregory/source/']

# php for `Post 1`
'php_post_1':
    build: 'php'
    container_name: 'php_post_1'
    volumes_from: ['source_post_1']
    volumes: ['./logs/php/post_1/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=post_1
      - AUTH_1_HOST=auth1.blog
      - AUTH_1_PORT=80
      - AUTH_2_HOST=auth2.blog
      - AUTH_2_PORT=80
    links:
      - mysql_blog
      - nginx_auth_1:auth1.blog
      - nginx_auth_2:auth2.blog


# nginx for `Post 1`
'nginx_post_1':
    build: 'nginx'
    container_name: 'nginx_post_1'
    links: ['php_post_1']
    volumes_from: ['source_post_1']
    environment:
      - PHP_HOST=php_post_1
      - NGINX_HOST_TEMPLATE=post1.blog
    volumes: ['./logs/nginx/post_1/:/var/log/nginx']

##########################################
# Service `Post 2`
##########################################

# source code storage for `Post 2`
'source_post_2':
    build: 'source'
    container_name: 'source_post_2'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Post:/home/gregory/source/']

# php for `Post 2`
'php_post_2':
    build: 'php'
    container_name: 'php_post_2'
    volumes_from: ['source_post_2']
    volumes: ['./logs/php/post_2/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=post_2
      - AUTH_1_HOST=auth1.blog
      - AUTH_1_PORT=80
      - AUTH_2_HOST=auth2.blog
      - AUTH_2_PORT=80
    links:
      - mysql_blog
      - nginx_auth_1:auth1.blog
      - nginx_auth_2:auth2.blog

# nginx for `Post 2`
'nginx_post_2':
    build: 'nginx'
    container_name: 'nginx_post_2'
    links: ['php_post_2']
    volumes_from: ['source_post_2']
    environment:
      - PHP_HOST=php_post_2
      - NGINX_HOST_TEMPLATE=post2.blog
    volumes: ['./logs/nginx/post_2/:/var/log/nginx']

##########################################
# Service `Comment 1`
##########################################

# source code storage for `Comment 1`
'source_comment_1':
    build: 'source'
    container_name: 'source_comment_1'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Comment:/home/gregory/source/']

# php for `Comment 1`
'php_comment_1':
    build: 'php'
    container_name: 'php_comment_1'
    volumes_from: ['source_comment_1']
    links: ['mysql_blog']
    volumes: ['./logs/php/comment_1/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=comment_1

# nginx for `Comment 1`
'nginx_comment_1':
    build: 'nginx'
    container_name: 'nginx_comment_1'
    links: ['php_comment_1']
    volumes_from: ['source_comment_1']
    environment:
      - PHP_HOST=php_comment_1
      - NGINX_HOST_TEMPLATE=comment1.blog
    volumes: ['./logs/nginx/comment_1/:/var/log/nginx']

##########################################
# Service `Comment 2`
##########################################

# source code storage for `Comment 2`
'source_comment_2':
    build: 'source'
    container_name: 'source_comment_2'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Comment:/home/gregory/source/']

# php for `Comment 2`
'php_comment_2':
    build: 'php'
    container_name: 'php_comment_2'
    volumes_from: ['source_comment_2']
    links: ['mysql_blog']
    volumes: ['./logs/php/comment_2/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=comment_2

# nginx for `Comment 2`
'nginx_comment_2':
    build: 'nginx'
    container_name: 'nginx_comment_2'
    links: ['php_comment_2']
    volumes_from: ['source_comment_2']
    environment:
      - PHP_HOST=php_comment_2
      - NGINX_HOST_TEMPLATE=comment2.blog
    volumes: ['./logs/nginx/comment_2/:/var/log/nginx']

##########################################
# Service `Auth 1`
##########################################

# source code storage for `Auth 1`
'source_auth_1':
    build: 'source'
    container_name: 'source_auth_1'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Auth:/home/gregory/source/']

# php for `Auth 1`
'php_auth_1':
    build: 'php'
    container_name: 'php_auth_1'
    volumes_from: ['source_auth_1']
    links: ['mysql_auth']
    volumes: ['./logs/php/auth_1/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_auth;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=auth_1

# nginx for `Auth 1`
'nginx_auth_1':
    build: 'nginx'
    container_name: 'nginx_auth_1'
    links: ['php_auth_1']
    volumes_from: ['source_auth_1']
    environment:
      - PHP_HOST=php_auth_1
      - NGINX_HOST_TEMPLATE=auth1.blog
    volumes: ['./logs/nginx/auth_1/:/var/log/nginx']

##########################################
# Service `Auth 2`
##########################################

# source code storage for `Auth 2`
'source_auth_2':
    build: 'source'
    container_name: 'source_auth_2'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Auth:/home/gregory/source/']

# php for `Auth 2`
'php_auth_2':
    build: 'php'
    container_name: 'php_auth_2'
    volumes_from: ['source_auth_2']
    links: ['mysql_auth']
    volumes: ['./logs/php/auth_2/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_auth;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root
      - NODE=auth_2

# nginx for `Auth 2`
'nginx_auth_2':
    build: 'nginx'
    container_name: 'nginx_auth_2'
    links: ['php_auth_2']
    volumes_from: ['source_auth_2']
    ports: ['30002:80']
    environment:
      - PHP_HOST=php_auth_2
      - NGINX_HOST_TEMPLATE=auth2.blog
    volumes: ['./logs/nginx/auth_2/:/var/log/nginx']